"""Regenerate the example CDIF documents from ``exampleData/``.

    python exampleMetadata/generate.py [--profile-dir DIR]

Everything it needs is in the repository, so this runs anywhere the
package does. The documents in this directory are *outputs*, not
fixtures: when the emitter changes, rerunning this is how they follow.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "src"))

from hdf5metadata.emit import emit_document                       # noqa: E402
from hdf5metadata.inspect import inspect_file, read_nexus         # noqa: E402
from hdf5metadata.map import load_crosswalk, map_nexus            # noqa: E402
from hdf5metadata.map.crosswalk import DATA_DIR                   # noqa: E402
from hdf5metadata.validate import (                               # noqa: E402
    find_profile,
    validate_document,
)

DATA = REPO / "exampleData"
SAS_CROSSWALK = DATA_DIR / "cdifsas-to-nexus.sssom.tsv"

#: (source file in exampleData/, crosswalk or None for the bundled XAS one)
EXAMPLES = [
    ("FeXAS.nxs", None),
    ("APS-USAXS-pinSAXS.hdf5", SAS_CROSSWALK),
    ("NXsas-autogenerated.hdf5", SAS_CROSSWALK),
    ("NXmx-Therm_6_2.nxs", None),
    ("NXtomo-autogenerated.hdf5", None),
    ("cu_metal_rt.nxs", None),
    ("cu_metal_10K.nxs", None),
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--profile-dir", type=Path,
        default=Path(r"C:/GithubC/CDIF/XAS-CDIF/release"),
        help="CDIF profile release directory, for validation")
    args = ap.parse_args()

    profile = find_profile(args.profile_dir)
    rows = []
    for filename, crosswalk_path in EXAMPLES:
        path = DATA / filename
        if not path.is_file():
            print(f"  skip {filename}: not in exampleData/")
            continue

        inspection = inspect_file(path)
        nexus = read_nexus(inspection)
        crosswalk = load_crosswalk(crosswalk_path) if crosswalk_path else None
        mapping = map_nexus(nexus, crosswalk)
        result = emit_document(inspection, nexus, mapping)

        out = HERE / (path.stem + ".jsonld")
        out.write_text(
            json.dumps(result.document, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")

        # Only check a document against a profile it actually claims. The
        # one profile release to hand is xasDocument; running a SAS or MX
        # document against it would report a long list of failures that
        # mean nothing, because the document never claimed to satisfy it.
        # "Not applicable" and "failed" are different answers.
        verdict = "n/a - no profile artifacts for the profiles claimed"
        if not profile.is_empty and "xasCore/1.0" in result.profiles:
            verdict = validate_document(result.document, profile).summary()

        rows.append((
            out.name, len(nexus.entries),
            max((len(r.values) for r in mapping.records), default=0),
            len(result.document.get("schema:variableMeasured", [])),
            ", ".join(p.split("/")[0] for p in result.profiles), verdict))
        print(f"  wrote {out.name}")

    print(f"\n{'document':32} {'ent':4} {'con':4} {'var':4} profiles")
    for name, ent, con, var, profiles, verdict in rows:
        print(f"{name:32} {ent:<4} {con:<4} {var:<4} {profiles}")
        print(f"{'':32} {verdict[:88]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
