"""Regenerate the example CDIF documents from ``exampleData/``.

    python exampleMetadata/generate.py [--profile-dir DIR]

Everything it needs is in the repository, so this runs anywhere the
package does. The documents in this directory are *outputs*, not
fixtures: when the emitter changes, rerunning this is how they follow.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "src"))

from hdf5metadata.emit import (                                   # noqa: E402
    HDF5_MEDIA_TYPE,
    XDI_MEDIA_TYPE,
    XDI_SPECIFICATION,
    emit_document,
)
from hdf5metadata.inspect import inspect_file, read_nexus         # noqa: E402
from hdf5metadata.inspect.xdi import inspect_xdi, is_xdi          # noqa: E402
from hdf5metadata.map import map_nexus                            # noqa: E402
from hdf5metadata.map.xdi import map_xdi                          # noqa: E402
from hdf5metadata.validate import (                               # noqa: E402
    find_profile,
    validate_document,
)

DATA = REPO / "exampleData"

#: No crosswalk is named for any of these. The mapper reads the
#: application definition each file declares and picks the crosswalk
#: itself, which is the whole point -- a mixed folder needs no per-file
#: configuration.
EXAMPLES = [
    "FeXAS.nxs",
    "APS-USAXS-pinSAXS.hdf5",
    "NXsas-autogenerated.hdf5",
    "NXmx-Therm_6_2.nxs",
    "NXtomo-autogenerated.hdf5",
    "cu_metal_rt.nxs",
    "cu_metal_10K.nxs",
    "CeO2.xdi",
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--profile-dir", type=Path,
        default=Path(r"C:/GithubC/CDIF/XAS-CDIF/release"),
        help="CDIF profile release directory, for validation")
    args = ap.parse_args()

    profile = find_profile(args.profile_dir)
    rows = []
    for filename in EXAMPLES:
        path = DATA / filename
        if not path.is_file():
            print(f"  skip {filename}: not in exampleData/")
            continue

        # Dispatch on what the file declares itself to be. XDI says so
        # on line 1; anything else is read as HDF5.
        if is_xdi(path):
            inspection, source = inspect_xdi(path)
            mapping = map_xdi(source)
            result = emit_document(
                inspection, source, mapping,
                encoding_format=XDI_MEDIA_TYPE,
                format_specification=XDI_SPECIFICATION)
        else:
            inspection = inspect_file(path)
            source = read_nexus(inspection)
            mapping = map_nexus(source)
            result = emit_document(
                inspection, source, mapping,
                encoding_format=HDF5_MEDIA_TYPE)
        nexus = source

        out = HERE / (path.stem + ".jsonld")
        out.write_text(
            json.dumps(result.document, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")

        # Only check a document against a profile it actually claims. The
        # one profile release to hand is xasDocument; running a SAS or MX
        # document against it would report a long list of failures that
        # mean nothing, because the document never claimed to satisfy it.
        # "Not applicable" and "failed" are different answers.
        verdict = "n/a - no profile artifacts for the profiles claimed"
        if not profile.is_empty and "xasCore/1.0" in result.profiles:
            verdict = validate_document(result.document, profile).summary()

        rows.append((
            out.name, len(nexus.entries),
            max((len(r.values) for r in mapping.records), default=0),
            len(result.document.get("schema:variableMeasured", [])),
            ", ".join(p.split("/")[0] for p in result.profiles), verdict,
            mapping.crosswalk_reason))
        print(f"  wrote {out.name}")

    print(f"\n{'document':32} {'ent':4} {'con':4} {'var':4} profiles")
    for name, ent, con, var, profiles, verdict, why in rows:
        print(f"{name:32} {ent:<4} {con:<4} {var:<4} {profiles}")
        print(f"{'':32} crosswalk: {why[:80]}")
        print(f"{'':32} {verdict[:88]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
